name: kyma-project.io/module/keda
channel: {{.Channel}}
version: {{.Version}}
defaultCR: config/samples/keda-default-cr.yaml
manifest: keda-manager.yaml
annotations:
  "operator.kyma-project.io/doc-url": "https://kyma-project.io/#/keda-manager/user/README"
moduleRepo: https://github.com/kyma-project/keda-manager.git