module-name: keda
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/keda-manager:1.3.0
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda:2.15.1
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-admission-webhooks:2.15.1
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-metrics-apiserver:2.15.1
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
