module-name: keda
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/keda-manager:v20230901-2a2e3f42
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda:2.11.2
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-admission-webhooks:2.11.2
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-metrics-apiserver:2.11.2
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
