module-name: keda
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/keda-manager:1.1.1
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda:2.12.0
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-admission-webhooks:2.12.0
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-metrics-apiserver:2.12.0
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
