apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: kyma-system
  labels:
    control-plane: manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: keda-manager.kyma-project.io
      control-plane: manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        sidecar.istio.io/inject: "false"
        rt-cfg.kyma-project.io/alter-img-registry: "true"
        rt-cfg.kyma-project.io/add-img-pull-secret: "true"
        rt-cfg.kyma-project.io/set-fips-mode: "true"
      labels:
        app.kubernetes.io/component: keda-manager.kyma-project.io
        control-plane: manager
    spec:
      priorityClassName: "priority-class"
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
            - --config-path=/logconfig/log-config.yaml
          image: controller:latest
          imagePullPolicy: Always
          name: manager
          volumeMounts:
            - name: log-configuration
              mountPath: /logconfig
          env:
            - name: LOG_CONFIG_PATH
              value: /logconfig/log-config.yaml
            - name: KEDA_MODULE_VERSION
              value: main
            - name: IMAGE_KEDA_OPERATOR
              value: europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda:2.18.3
            - name: IMAGE_KEDA_METRICS_APISERVER
              value: europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-metrics-apiserver:2.18.3
            - name: IMAGE_KEDA_ADMISSION_WEBHOOKS
              value: europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-admission-webhooks:2.18.3
            - name: IMAGE_KEDA_OPERATOR_FIPS
              value: europe-docker.pkg.dev/kyma-project/restricted-prod/sap.com/keda-fips:2.18.2
            - name: IMAGE_KEDA_METRICS_APISERVER_FIPS
              value: europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-metrics-apiserver-fips:2.18.2
            - name: IMAGE_KEDA_ADMISSION_WEBHOOKS_FIPS
              value: europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-admission-webhooks-fips:2.18.2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 512Mi
              cpu: 200m
      volumes:
        - name: log-configuration
          configMap:
            name: log-configmap
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
