# this is set of overwrites used to template this chart:
# https://github.com/kedacore/charts/tree/main/keda

global:
  image:
    registry: "europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io"

prometheus:
  metricServer:
    enabled: true
  operator:
    enabled: true
  webhooks:
    enabled: true

logging:
  operator:
    level: "info"
    format: "json"
    timeEncoding: "rfc3339"
  metricServer:
    zapLevel: "info"
    zapEncoder: "json"
    zapTimeEncoding: "rfc3339"
  webhooks:
    level: "info"
    format: "json"
    timeEncoding: "rfc3339"


http:
  minTlsVersion: TLS12

image:
  pullPolicy: IfNotPresent