apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-target
  namespace: keda-custom-metric-api
  labels:
    app.kubernetes.io/name: scale-target
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scale-target
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scale-target
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80