name: keda build (pull)

on:
  workflow_call:
  pull_request_target:
    paths-ignore:
      - "docs/**"
      - "examples/**"
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-keda-manager:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: keda-manager
      dockerfile: Dockerfile
