name: Keda verify

env:
  GO_VERSION: '1.22'

on:
  push:
    branches: [ "main", "release-*" ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft

jobs:
  # pre-keda-manager-operator-lint
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: $GO_VERSION
      - uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          working-directory: '.'
  # pre-keda-manager-operator-tests
  unit-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: $GO_VERSION
      - name: run test
        run: make test
  
  # pre-keda-manager-verify
  integration-test:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: $GO_VERSION
      - name: create single cluster
        uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
        with:
          cluster-name: "k3dCluster"
          args: >-
            --agents 1
            --port 80:80@loadbalancer
            --port 443:443@loadbalancer
            --image rancher/k3s:v1.28.6-k3s1
            --wait
      - name: run test
        run: make -C hack/ci integration-test-on-cluster
        env:
          IMG: europe-docker.pkg.dev/kyma-project/dev/keda-manager:PR-${{ github.event.number }}
  # post-keda-manager-upgrade-latest-to-main
  upgrade-test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: $GO_VERSION
      - name: create single cluster
        uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
        with:
          cluster-name: "k3dCluster"
          args: >-
            --agents 1
            --port 80:80@loadbalancer
            --port 443:443@loadbalancer
            --image rancher/k3s:v1.28.6-k3s1
            --wait
      - name: run test
        run: make -C hack/ci upgrade-test
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/keda-manager:${{ github.sha }}
