name: pull
on:
  pull_request_target:
    branches:
      - main
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  unit-tests:
    uses: kyma-project/keda-manager/.github/workflows/_unit-tests.yaml@main

  gitleaks:
    uses: kyma-project/keda-manager/.github/workflows/_gitleaks.yaml@main

  builds:
    uses: kyma-project/keda-manager/.github/workflows/_build.yaml@main

  integrations:
    needs: builds
    uses: kyma-project/keda-manager/.github/workflows/_integration-tests.yaml@main
    with:
      image: europe-docker.pkg.dev/kyma-project/dev/keda-manager:PR-${{ github.event.number }}
